package items

type stats struct {
	Mana                   int
	Health                 int
	Agility                int
	Strength               int
	Intellect              int
	Spirit                 int
	Stamina                int
	DefenseSkillRating     int
	DodgeRating            int
	ParryRating            int
	BlockRating            int
	HitMeleeRating         int
	HitRangedRating        int
	HitSpellRating         int
	CritMeleeRating        int
	CritRangedRating       int
	CritSpellRating        int
	HitTakenMeleeRating    int
	HitTakenRangedRating   int
	HitTakenSpellRating    int
	CritTakenMeleeRating   int
	CritTakenRangedRating  int
	CritTakenSpellRating   int
	HasteMeleeRating       int
	HasteRangedRating      int
	HasteSpellRating       int
	HitRating              int
	CritRating             int
	HitTakenRating         int
	CritTakenRating        int
	ResilienceRating       int
	HasteRating            int
	ExpertiseRating        int
	AttackPower            int
	RangedAttackPower      int
	FeralAttackPower       int
	SpellHealingDone       int
	SpellDamageDone        int
	ManaRegeneration       int
	ArmorPenetrationRating int
	SpellPower             int
	HealthRegen            int
	SpellPenetration       int
	BlockValue             int
}

var STAT = stats{
	Mana:                   0,
	Health:                 1,
	Agility:                3,
	Strength:               4,
	Intellect:              5,
	Spirit:                 6,
	Stamina:                7,
	DefenseSkillRating:     12,
	DodgeRating:            13,
	ParryRating:            14,
	BlockRating:            15,
	HitMeleeRating:         16,
	HitRangedRating:        17,
	HitSpellRating:         18,
	CritMeleeRating:        19,
	CritRangedRating:       20,
	CritSpellRating:        21,
	HitTakenMeleeRating:    22,
	HitTakenRangedRating:   23,
	HitTakenSpellRating:    24,
	CritTakenMeleeRating:   25,
	CritTakenRangedRating:  26,
	CritTakenSpellRating:   27,
	HasteMeleeRating:       28,
	HasteRangedRating:      29,
	HasteSpellRating:       30,
	HitRating:              31,
	CritRating:             32,
	HitTakenRating:         33,
	CritTakenRating:        34,
	ResilienceRating:       35,
	HasteRating:            36,
	ExpertiseRating:        37,
	AttackPower:            38,
	RangedAttackPower:      39,
	FeralAttackPower:       40,
	SpellHealingDone:       41,
	SpellDamageDone:        42,
	ManaRegeneration:       43,
	ArmorPenetrationRating: 44,
	SpellPower:             45,
	HealthRegen:            46,
	SpellPenetration:       47,
	BlockValue:             48,
}
